name: transitflow_administrator
description: Flutter-based desktop application for managing users, transactions, and system operations within the TransitFlow platform.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^0.66.0
  excel: ^4.0.4
  csv: ^6.0.0
  pdf: ^3.11.1
  path_provider: ^2.1.4
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
